# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: zooeymoon1989/mongo-tls
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
    container_name: mongo-tls
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    entrypoint: 
      - mongod 
      - --config
      - /etc/mongo.conf