FROM mongo

COPY ./scripts /home/mongodb/scripts

COPY ./keys /home/mongodb/ssl

COPY ./mongo-server/mongod.conf /home/mongodb

WORKDIR /home/mongodb

RUN ["chmod", "-R","0777", "/home/mongodb/scripts/"]

CMD ["/home/mongodb/scripts/run.sh"]