# traefik-tls-conf.yml
tcp :
  routers :
    mosquitto-router :
      entryPoints :
      - websecure
      rule : "HostSNI(`mosquitto.liwenqiang.site`)"
      service : mosquitto-tcp-service
      tls: {} #This block will enable TLS for this route

#We also need to provide the TLS certificates
tls:
  certificates:
    - certFile: tls/mosquitto.liwenqiang.site.pem
      # keyFile: localhost+1-key.pem