# traefik.yml with only 443 entrypoint
entryPoints:
  mosquitto:
    address: ":18883"
  https:
    address: ":443"
  http: 
    address: ":80"
    # force redirecting scheme from http to https 
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

# Also enable DEBUG log
log:
  level: DEBUG
providers:
  file:
    filename: "traefik-tls-conf.yml"
    watch: true

# API and dashboard configuration
api:
  insecure: true
  dashboard: true