# traefik-tls-conf.yml
tcp :
  routers :
    mosquitto-router :
      entryPoints :
      - websecure
      rule : "HostSNI(`mosquitto.liwenqiang.site`)"
      service : mosquitto-tcp-service
      # tls:
      #   certResolver: "letsencrypt"
      #   domains:
      #     - main: "tlstraefik.rahulsharma.page"
      tls: {} #This block will enable TLS for this route
  services:
    mosquitto-tcp-service: 
      loadBalancer:
        servers:
        - address: "43.131.242.103:8883"
#We also need to provide the TLS certificates
tls:
  certificates:
    - certFile: /root/study-traefik/chapter4/tls/mosquitto.liwenqiang.site.pem
      # keyFile: localhost+1-key.pem