# traefik-tls-conf.yml
tcp :
  routers :
    mosquitto-router :
      entryPoints :
      - mosquitto
      rule : "HostSNI(`mosquitto.liwenqiang.site`)"
      service : mosquitto-tcp-service
      # tls:
      #   certResolver: "letsencrypt"
      #   domains:
      #     - main: "tlstraefik.rahulsharma.page"
      tls: {} #This block will enable TLS for this route
  services:
    mosquitto-tcp-service: 
      loadBalancer:
        servers:
        - address: "127.0.0.1:8884"
#We also need to provide the TLS certificates
tls:
  certificates:
    - certFile: /etc/mosquitto/certs/server.crt
      keyFile: /etc/mosquitto/certs/server.key