# traefik.yml with only 443 entrypoint
entryPoints:
  mosquitto:
    address: ":8883"
  websecure:
    address: ":443"

# Also enable DEBUG log
log:
  level: DEBUG
providers:
  file:
    filename: "traefik-tls-conf.yml"
    watch: true

# API and dashboard configuration
api:
  insecure: true
  dashboard: true