entryPoints :
  web :
    address : ":80"

providers :
  directory : /root/study-traefik/chapter5
  watch : true
  filename : traefik-config.yml
  debugLogGeneratedTemplate : true

api :
  insecure : true
  dashboard : true

