entryPoints :
  web :
    address : ":80"

providers :
  file:
    directory : /root/study-traefik/chapter5
    watch : true
    filename : traefik-config.yml
    debugLogGeneratedTemplate : true

api :
  insecure : true
  dashboard : true

accessLog:
  filePath: access.log
  # filePath: /var/log/traefik/traefik.log # need to create relative dir first
  bufferingSize: 50
  filters:
    statusCodes:
      - "200"
      - 300-302
    retryAttempts: true
    minDuration: 5s
    fields:
      defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
          User-Agent: redact
          Authorization: drop
          Content-Type: keep