entryPoints :
  web :
    address : ":80"

providers :
  file:
    directory : /root/study-traefik/chapter5
    watch : true
    filename : traefik-config.yml
    debugLogGeneratedTemplate : true

api :
  insecure : true
  dashboard : true

accessLog:
  # filePath: access.log
  filePath: /var/log/traefik/traefik.log # need to create relative dir first
  bufferingSize: 50
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
          User-Agent: redact
          Authorization: drop
          Content-Type: keep
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: 10ms

tracing:
  zipkin:
    # HTTP endpoint used to send data.
    httpEndpoint: http://localhost:9411/api/v2/spans
    # Uses 128 bits trace IDs.
    id128Bit : true
    # Uses SameSpan RPC style traces.
    sameSpan: true