apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
  - host: k8s.liwenqiang.site
    http:
      paths:
      - path: /golang
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 8000