apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-consul-consul-server
  labels:
    volume: data-vault-consul-consul-server
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/consul-storage"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-vault-consul-consul-server-0
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-vault-consul-consul-server

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-vault-consul-consul-server-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-vault-consul-consul-server

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-vault-consul-consul-server-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-vault-consul-consul-server

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-vault-consul-consul-server-3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-vault-consul-consul-server