apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-consul-server-0
  labels:
    volume: data-consul-consul-server-0
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: 10.0.0.11
    path: /vdb/v0
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-consul-server-1
  labels:
    volume: data-consul-consul-server-1
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: 10.0.0.11
    path: /vdb/v1
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-consul-server-2
  labels:
    volume: data-consul-consul-server-2
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: 10.0.0.11
    path: /vdb/v2
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-consul-server-3
  labels:
    volume: data-consul-consul-server-3
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: 10.0.0.11
    path: /vdb/v3