kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-consul-consul-server-0
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-consul-consul-server-0

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-consul-consul-server-1
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-consul-consul-server-1

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-consul-consul-server-2
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-consul-consul-server-2

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-consul-consul-server-3
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: data-consul-consul-server-3